### ISSUE TITLE
Blurry window buttons

### ISSUE THREAD

**Issue by DarthWound** [linuxdeepin/deepin-gtk-theme#10]
Hello Deepin team, thank you for your nice work.

1) It's not a new issue, but close 'X' button is blurry, at least on GNOME, but I remember having the same problem in a Deepin vm. It's sad because other buttons are beautifully sharp.

2) In GNOME Terminal, and maybe some other apps, all three buttons are blurry.

![capture d ecran de 2018-03-06 21-31-16](https://user-images.githubusercontent.com/1771322/37057272-1eddc89e-2187-11e8-8901-42fb2ee0119a.png)

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
