### ISSUE TITLE
Theme parsing error: gtk.css:3601  'none' is not a valid color name

### ISSUE THREAD

**Issue by sgse** [linuxdeepin/deepin-gtk-theme#11]
Hello,

about 
(gnome-clocks:22881): Gtk-WARNING **: 
Theme parsing **error**: gtk.css:3601:22: 'none' is not a valid color name.

 deepin-gtk-theme/deepin-dark/gtk-3.0/gtk.css

line 3601 
border-color: **none**; 
to 
border-color: **transparent**;

Found in https://bugs.archlinux.org/task/57058 helpful for me, maybe for other too.
Greetings sgse

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
