### ISSUE TITLE
annoying GTK color difference in some applications on window decoration vs menu.

### ISSUE THREAD

**Issue by otavioschwanck** [linuxdeepin/deepin-gtk-theme#12]
Deepin is one of the most beautiful GTK themes, but this is really annoying.

Visual Studio Code:
![image](https://user-images.githubusercontent.com/9551316/43236377-2daadafe-905b-11e8-9841-e5ee32cf3c7a.png)

Franz:

![image](https://user-images.githubusercontent.com/9551316/43236487-be99212e-905b-11e8-855f-78bfb4693281.png)

Arc Theme Comparassion:
![image](https://user-images.githubusercontent.com/9551316/43236576-422478f4-905c-11e8-91ed-3dd80559b3e6.png)
window top bar and menu background in the same color <3.

**Comment by BLumia** [comment]
@hualet

**Comment by hualet** [comment]
@otavioschwanck See if https://github.com/linuxdeepin/developer-center/wiki/Contribution-Guidelines-for-Developers-en helps ?

**Comment by otavioschwanck** [comment]
Fixed on https://github.com/linuxdeepin/deepin-gtk-theme/pull/14

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
