### ISSUE TITLE
 deepin gtk theme for xfce4 desktop  shows arc white window manager theme 

### ISSUE THREAD

**Issue by elswerky** [linuxdeepin/deepin-gtk-theme#16]
can you please add support for xfce4 desktop for this theme 
because if i choose deepin gtk theme for windows manager in xfce4 desktop instead of showing new window theme for deepin-gtk ,,it shows white arc theme although am not installing arc-gtk theme ( i talk about windows manager theme in xfce4 ) 

i know it is strange to ask such question for other desktops as this theme is for deepin desktop environment not other desktops

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
