### ISSUE TITLE
gtk3.20

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/deepin-gtk-theme#2]
On Archlinux and Arch-based systems gtk3.20 has already arrived. Are you planning to release a 3.20 version of **deepin-gtk-theme** in the near future? Or will we have to look for alternatives meanwhile?
greetings
oberon

**Comment by oberon2007** [comment]
The situation is aggravated by the problem that even up-front themes like **vertex** fail to decorate windows under mutter/gala for gtk3 and qt applications

![deepinscreenshot20160421222704](https://cloud.githubusercontent.com/assets/11800714/14723312/acf2cc7a-0810-11e6-8424-739be4f1d4ea.png)

Only when switching to metacity mode I can get proper theming at the moment...

**Comment by fasheng** [comment]
Well, someone reported it before, I think we could fix it soon this time...

**Comment by manateelazycat** [comment]
![20160707151708](https://cloud.githubusercontent.com/assets/237487/16645354/f2fc4f62-4455-11e6-8beb-41c0de2a535f.png)
![20160707151718](https://cloud.githubusercontent.com/assets/237487/16645355/f3429828-4455-11e6-8e5b-4032f8656eae.png)

We have fixed this problem, please install lastest version of deepin and dist-upgrade system, you will found theme has support gtk 3.20

Thanks for report!

**Comment by oberon2007** [comment]
If that's the case, the latest [release](https://github.com/linuxdeepin/deepin-gtk-theme/releases/tag/15.12.6) of **deepin-gtk-theme** seems to be not up-to-date. It's from February 19 :stuck_out_tongue_winking_eye:

**Comment by oberon2007** [comment]
Or else we should use the gtk3.20 branch to create the Archlinux package @felixonmars ?

**Comment by oberon2007** [comment]
I just see that both master and gtk3.20 branches are empty and the develop branch is old... :laughing: Has the content been moved somewhere else?
