### ISSUE TITLE
Menubar does match nicely

### ISSUE THREAD

**Issue by markbaas** [linuxdeepin/deepin-gtk-theme#3]
In chrome and electron application (vscode, slack, etc), the menubar looks out-of-theme. This doesn't happen with other themes such as arc.

![deepinscreenshot20160819113539](https://cloud.githubusercontent.com/assets/1153495/17815213/49237286-6601-11e6-92cf-8a1ea9318648.png)
![deepinscreenshot20160819113647](https://cloud.githubusercontent.com/assets/1153495/17815215/494e3a48-6601-11e6-8b3e-d97aee88bf7b.png)

ps. I can't get almost any other theme to work nicely, probably because of latest version of debian packages.

**Comment by fasheng** [comment]
Thanks, got it~

**Comment by otavioschwanck** [comment]
fixed on https://github.com/linuxdeepin/deepin-gtk-theme/pulls/14

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
