### ISSUE TITLE
Red bar on some applications (with darkblue underline)

### ISSUE THREAD

**Issue by Pandiora** [linuxdeepin/deepin-gtk-theme#4]
Hey there,

I recently installed Manjaro Deepin (based on Arch) and discovered, that the "deepin-dark"-Theme shows some red bar on active windows with a blue underline. It looks like someone forgot to change the background-colors for these kind of elements/states. ;) Arch links to your Github-Repo for this theme, so I hope I'm right here.

Remmina focused:
![Remmina:](http://i.imgur.com/uekMSEJ.png)
System-Monitor focused:
![System-Monitor:](http://i.imgur.com/EtUqKdE.png)
Both w/o focus (focus on config-panel on the right side):
![Both w/o focus:](http://i.imgur.com/vFdlfrW.png)

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
