### ISSUE TITLE
Title bar color mismatch (window effect mode: off)

### ISSUE THREAD

**Issue by unc926** [linuxdeepin/deepin-gtk-theme#9]
**Normal Screen:**

![deepinscreenshot_select-area_20170916164915](https://user-images.githubusercontent.com/30185386/30512775-48590d64-9aff-11e7-9b6f-9ae14e2682ea.png)

**Full Screen:**

![deepinscreenshot_select-area_20170916164934](https://user-images.githubusercontent.com/30185386/30512774-48375110-9aff-11e7-9bad-7ebfc7b99240.png)

If there is a quick solution, add a note here. Thank you.

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
